import type {
  FleetState,
  ShipState,
  ConvoyState,
  GameWorldState,
  UniverseData,
  AtlasData,
  StarSystemInfo,
  StaticTileSystem,
  DynamicTileSystem,
  MarketEntry,
  MarketComparisonEntry,
  GoodInfo,
  TradeHistoryEntry,
  TradeType,
  ActiveEvent,
  SystemPriceHistory,
  TradeMissionInfo,
  MissionInfo,
  BattleInfo,
  BattleDetailInfo,
  TraitId,
  TraitCategory,
  QualityTier,
  PlayerNotificationInfo,
  SunClass,
  BodyArchetypeId,
  StabilityEntry,
  ResourceVector,
} from "./game";
import type { GlobalEventMap, PlayerEventMap } from "@/lib/tick/types";
import type { SubstrateGoodRate } from "@/lib/engine/physical-economy";

// ── Responses ────────────────────────────────────────────────────

export interface ApiResponse<T> {
  data?: T;
  error?: string;
}

export type FleetResponse = ApiResponse<FleetState>;
export type GameWorldResponse = ApiResponse<GameWorldState>;
export type UniverseResponse = ApiResponse<UniverseData>;
export type AtlasResponse = ApiResponse<AtlasData>;
export type StaticTileResponse = ApiResponse<{ systems: StaticTileSystem[] }>;
export type DynamicTileResponse = ApiResponse<{ systems: DynamicTileSystem[] }>;
export type VisibilityResponse = ApiResponse<{ systemIds: string[] }>;
export interface TradeFlowEdgeInfo {
  /** Net source system for the dominant good (where particles spawn). */
  fromSystemId: string;
  /** Net destination system for the dominant good (where particles terminate). */
  toSystemId: string;
  /** Sum of magnitudes across both directions and all goods. */
  totalVolume: number;
  dominantGoodId: string;
  /** Per-good magnitude (both directions summed). */
  perGood: Record<string, number>;
}
export type TradeFlowResponse = ApiResponse<{ edges: TradeFlowEdgeInfo[] }>;
export type StabilityResponse = ApiResponse<{ systems: StabilityEntry[] }>;
/** Aggregate trading partner for a single good (top-N source or destination). */
export interface TradeFlowPartner {
  systemId: string;
  systemName: string;
  quantity: number;
}
/** One good's total flow and the top partner systems that contributed. */
export interface TradeFlowGoodSummary {
  goodId: string;
  goodName: string;
  totalQuantity: number;
  partners: TradeFlowPartner[];
}
/** One bucket of the import/export volume sparkline. `tick` is the bucket end. */
export interface TradeFlowVolumeBucket {
  tick: number;
  importVolume: number;
  exportVolume: number;
}
export interface SystemTradeFlowData {
  topImports: TradeFlowGoodSummary[];
  topExports: TradeFlowGoodSummary[];
  volumeHistory: TradeFlowVolumeBucket[];
}
export type SystemTradeFlowResponse = ApiResponse<SystemTradeFlowData>;
/** Enriched trait data returned from system detail API. */
export interface SystemTraitResponse {
  traitId: TraitId;
  quality: QualityTier;
  name: string;
  category: TraitCategory;
  description: string;
}

/** Full system detail — discriminated union on visibility. */
export type SystemDetailData =
  | (StarSystemInfo & {
      visibility: "visible";
      station: { id: string; name: string } | null;
      traits: SystemTraitResponse[];
    })
  | {
      id: string;
      name: string;
      economyType: StarSystemInfo["economyType"];
      regionId: string;
      isGateway: boolean;
      visibility: "unknown";
    };
export type SystemDetailResponse = ApiResponse<SystemDetailData>;

// ── System population ────────────────────────────────────────────
/** One good's contribution to the population demand footprint. */
export interface PopulationDemandEntry {
  goodId: string;
  goodName: string;
  /** Demand rate (units/tick) generated by this system's population. */
  demandRate: number;
}

/** Dynamic population & social state for one system — discriminated on visibility. */
export type SystemPopulationData =
  | {
      visibility: "visible";
      population: number;
      popCap: number;
      unrest: number;
      /** True when unrest ≥ STRIKE_PARAMS.threshold. */
      striking: boolean;
      /** Top-N goods by demand rate, descending. */
      demand: PopulationDemandEntry[];
    }
  | { visibility: "unknown" };
export type SystemPopulationResponse = ApiResponse<SystemPopulationData>;

// ── System substrate (physical / static — astrography flavour) ───────────────
export interface BodyView {
  id: string;
  bodyType: BodyArchetypeId;
  archetypeName: string;
  habitable: boolean;
  size: number;
  /** Per-resource deposit slots on this body (0 = no deposit). */
  slots: ResourceVector;
  /** Per-resource intrinsic quality multiplier on this body (0 = no deposit). */
  quality: ResourceVector;
}
/**
 * Physical substrate for one system — the static "what is physically here":
 * star, surface size, habitable fraction, bodies, and the deposits they host.
 * Discriminated on fog-of-war visibility. (Built-out / production state lives on
 * the tick-aware industry read.)
 */
export type SystemSubstrateData =
  | {
      visibility: "visible";
      sunClass: SunClass;
      /** Total available surface space across all bodies (SPACE_PER_SIZE × Σ size). */
      availableSpace: number;
      /** Habitable surface across all bodies. */
      habitableSpace: number;
      bodies: BodyView[];
    }
  | { visibility: "unknown" };
export type SystemSubstrateResponse = ApiResponse<SystemSubstrateData>;

// ── System industry (built base + supply-chain + output — functional/dynamic) ─
import type {
  SystemIndustryReadout,
  SubstrateSpace,
  SystemDepositSummary,
} from "@/lib/engine/industry";
export type { SystemIndustryReadout, SubstrateSpace, SystemDepositSummary, SubstrateGoodRate };
/**
 * Industrial base, development headroom, deposit-fill, supply-chain and
 * production/consumption for one system — discriminated on visibility.
 */
export type SystemIndustryData =
  | ({
      visibility: "visible";
      /** Available-space partition + built-out land per partition (headroom). */
      space: SubstrateSpace;
      /** Per-resource deposit-fill rows: slot cap, worked slots, effective yield + band. */
      deposits: SystemDepositSummary[];
      /** Per-good production vs consumption from the built base + population (real yields). */
      goods: SubstrateGoodRate[];
    } & SystemIndustryReadout)
  | { visibility: "unknown" };
export type SystemIndustryResponse = ApiResponse<SystemIndustryData>;

export type MarketResponse = ApiResponse<{ stationId: string; entries: MarketEntry[] }>;
export type MarketComparisonResponse = ApiResponse<{ goodId: string; entries: MarketComparisonEntry[] }>;
export type GoodsResponse = ApiResponse<{ goods: GoodInfo[] }>;
export type TradeHistoryResponse = ApiResponse<TradeHistoryEntry[]>;
export type EventsResponse = ApiResponse<ActiveEvent[]>;
export type PriceHistoryResponse = ApiResponse<SystemPriceHistory[]>;

import type { PlayerFactionReputationInfo } from "@/lib/services/reputation";
export type ReputationResponse = ApiResponse<PlayerFactionReputationInfo[]>;

import type {
  FactionSummary,
  FactionDetail,
  RelationsMatrixData,
} from "@/lib/services/factions";
export type FactionListResponse = ApiResponse<FactionSummary[]>;
export type FactionDetailResponse = ApiResponse<FactionDetail>;
export type RelationsMatrixResponse = ApiResponse<RelationsMatrixData>;

export interface ShipTradeResult {
  ship: ShipState;
  updatedMarket: MarketEntry;
}
export type ShipTradeResponse = ApiResponse<ShipTradeResult>;

export interface ShipNavigateResult {
  ship: ShipState;
  fuelUsed: number;
  travelDuration: number;
}
export type ShipNavigateResponse = ApiResponse<ShipNavigateResult>;

/** Client-facing tick event (per-player filtered by SSE route). */
export interface TickEvent {
  currentTick: number;
  tickRate: number;
  /** Merged global events from all processors. */
  events: Partial<GlobalEventMap>;
  /** Player-scoped events (filtered to this client). */
  playerEvents: Partial<PlayerEventMap>;
  /** Which processors ran this tick (dev/debug only). */
  processors?: string[];
}

// ── Requests ─────────────────────────────────────────────────────

export interface ShipTradeRequest {
  stationId: string;
  goodId: string;
  quantity: number;
  type: TradeType;
}

export interface ShipNavigateRequest {
  route: string[]; // ordered [origin, ...hops, destination]
}

export interface ShipRefuelRequest {
  amount: number;
}

export interface ShipRefuelResult {
  ship: ShipState;
  creditSpent: number;
}
export type ShipRefuelResponse = ApiResponse<ShipRefuelResult>;

export interface ShipPurchaseRequest {
  systemId: string;
  shipType: string;
}

export interface ShipPurchaseResult {
  ship: ShipState;
  creditSpent: number;
}
export type ShipPurchaseResponse = ApiResponse<ShipPurchaseResult>;

// ── Mission types ───────────────────────────────────────────────

export interface SystemMissionsData { available: TradeMissionInfo[]; active: TradeMissionInfo[] }
export type SystemMissionsResponse = ApiResponse<SystemMissionsData>;

export interface AcceptMissionRequest { missionId: string }
export interface AcceptMissionResult { mission: TradeMissionInfo; activeCount: number }
export type AcceptMissionResponse = ApiResponse<AcceptMissionResult>;

export interface DeliverMissionRequest { missionId: string; shipId: string }
export interface DeliverMissionResult { mission: TradeMissionInfo; goodsValue: number; reward: number; creditEarned: number; newBalance: number }
export type DeliverMissionResponse = ApiResponse<DeliverMissionResult>;

export interface AbandonMissionRequest { missionId: string }
export type AbandonMissionResponse = ApiResponse<{ missionId: string }>;

// ── Operational mission types ───────────────────────────────────

export interface SystemAllMissionsData {
  tradeMissions: { available: TradeMissionInfo[]; active: TradeMissionInfo[] };
  opMissions: { available: MissionInfo[]; active: MissionInfo[] };
}
export type SystemAllMissionsResponse = ApiResponse<SystemAllMissionsData>;

export interface AcceptOpMissionResult { mission: MissionInfo }
export type AcceptOpMissionResponse = ApiResponse<AcceptOpMissionResult>;

export interface StartOpMissionRequest { shipId: string }
export interface StartOpMissionResult { mission: MissionInfo }
export type StartOpMissionResponse = ApiResponse<StartOpMissionResult>;

export type AbandonOpMissionResponse = ApiResponse<{ missionId: string }>;

// ── Battle types ───────────────────────────────────────────────

export type BattlesResponse = ApiResponse<BattleInfo[]>;
export type BattleDetailResponse = ApiResponse<BattleDetailInfo>;

// ── Convoy types ────────────────────────────────────────────────

export type ConvoyListResponse = ApiResponse<ConvoyState[]>;

export interface CreateConvoyRequest { shipIds: string[]; name?: string }
export interface CreateConvoyResult { convoy: ConvoyState }
export type CreateConvoyResponse = ApiResponse<CreateConvoyResult>;

export interface ConvoyMemberRequest { shipId: string }
export interface ConvoyBatchMemberRequest { shipIds: string[] }
export type ConvoyMemberResponse = ApiResponse<ConvoyState>;

export interface ConvoyNavigateRequest { route: string[] }
export type ConvoyNavigateResponse = ApiResponse<{ convoy: ConvoyState; fuelUsed: number; travelDuration: number }>;

// ── Convoy trade types ─────────────────────────────────────────

export interface ConvoyTradeResult { updatedMarket: MarketEntry }
export type ConvoyTradeResponse = ApiResponse<ConvoyTradeResult>;

// ── Convoy repair types ────────────────────────────────────────

export interface ConvoyRepairRequest { fraction: number }
export interface ConvoyRepairResult { totalCost: number; totalHealed: number }
export type ConvoyRepairResponse = ApiResponse<ConvoyRepairResult>;

// ── Convoy refuel types ────────────────────────────────────────

export interface ConvoyRefuelRequest { fraction: number }
export interface ConvoyRefuelResult { totalCost: number; totalFueled: number }
export type ConvoyRefuelResponse = ApiResponse<ConvoyRefuelResult>;

// ── Upgrade types ───────────────────────────────────────────────

export interface InstallUpgradeRequest { slotId: string; moduleId: string; tier?: number }
export interface InstallUpgradeResult { ship: ShipState; creditSpent: number }
export type InstallUpgradeResponse = ApiResponse<InstallUpgradeResult>;

export interface RemoveUpgradeRequest { slotId: string }
export type RemoveUpgradeResponse = ApiResponse<{ ship: ShipState }>;

// ── Repair types ────────────────────────────────────────────────

export interface RepairResult { ship: ShipState; creditSpent: number }
export type RepairResponse = ApiResponse<RepairResult>;

// ── Pagination types ────────────────────────────────────────────

/** Shared paginated response shape — all paginated endpoints return this. */
export interface PaginatedData<T> {
  items: T[];
  nextCursor: string | null;
  total: number;
}
export type PaginatedResponse<T> = ApiResponse<PaginatedData<T>>;

// ── Notification types ──────────────────────────────────────────

export type NotificationsResponse = PaginatedResponse<PlayerNotificationInfo>;
export type UnreadCountResponse = ApiResponse<{ count: number }>;
export type MarkReadResponse = ApiResponse<{ marked: number }>;

// ── Auth types ──────────────────────────────────────────────────

export interface RegisterRequest {
  name: string;
  email: string;
  password: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}
